CREATE TABLE [dbo].[ImxDirect_WirePricingInfo] (
    [WireId]                 INT              NOT NULL,
    [PreparationId]          UNIQUEIDENTIFIER NOT NULL,
    [PreparationDatetime]    DATETIME         NULL,
    [AgSenderCode]           VARCHAR (10)     NULL,
    [AgPayerCode]            VARCHAR (10)     NULL,
    [DestCountryAbbr]        VARCHAR (3)      NULL,
    [TranTypeId]             INT              NULL,
    [DeliveryType]           CHAR (1)         NULL,
    [SenderPaymentMethodId]  INT              NULL,
    [OriCurrencyCode]        VARCHAR (3)      NULL,
    [OriAmount]              MONEY            NULL,
    [AgPlanAssignId]         INT              NULL,
    [FeePlanID]              INT              NULL,
    [CommPlanID]             INT              NULL,
    [ExRatePlanID]           INT              NULL,
    [FXDif]                  DECIMAL (17, 4)  NULL,
    [FXShareId]              INT              NULL,
    [RateTypeId]             INT              NULL,
    [PriceAffectedBy]        VARCHAR (10)     NULL,
    [PlanFeeAmount]          MONEY            NULL,
    [WireFeeAmount]          MONEY            NULL,
    [PlanCommissionAmount]   MONEY            NULL,
    [WireCommissionAmount]   MONEY            NULL,
    [PlanEXRate]             MONEY            NULL,
    [WireEXRate]             MONEY            NULL,
    [DestAmount]             MONEY            NULL,
    [DestCurrencyCode]       VARCHAR (3)      NULL,
    [WireStateFee]           MONEY            NULL,
    [DiscountAmount]         MONEY            NULL,
    [PromotionId]            INT              NULL,
    [PromoCode]              VARCHAR (20)     NULL,
    [PromoType]              CHAR (2)         NULL,
    [PromoCost]              MONEY            NULL,
    [PromoCostToCompany]     MONEY            NULL,
    [PromoCostToAgent]       MONEY            NULL,
    [PromoCostToPayer]       MONEY            NULL,
    [PromoFxDif]             DECIMAL (10, 4)  NULL,
    [PromoFxCost]            MONEY            NULL,
    [PromoResultWirePoints]  INT              NULL,
    [WiresAlreadyCountGUID]  UNIQUEIDENTIFIER NULL,
    [PointsToRedeem]         INT              NULL,
    [PointsRedemptionId]     INT              NULL,
    [PointsRedemptionType]   VARCHAR (5)      NULL,
    [PointsRedemptionValue]  DECIMAL (10, 4)  NULL,
    [PointsRedemptionCost]   MONEY            NULL,
    [FlexPriceOption]        CHAR (3)         NULL,
    [FlexPriceValueApplied]  DECIMAL (10, 4)  NULL,
    [FlexPriceCost]          MONEY            NULL,
    [FlexPriceCostApplyTo]   CHAR (1)         NULL,
    [PayerPromId]            INT              NULL,
    [PayerPromFxAdded]       DECIMAL (10, 4)  NULL,
    [DestAmountMultipleOf]   MONEY            DEFAULT ((0)) NULL,
    [DestAmountIsOK]         BIT              DEFAULT ((1)) NULL,
    [StsComplianceOk]        BIT              DEFAULT ((0)) NULL,
    [AgencyFee]              MONEY            DEFAULT ((0)) NULL,
    [SenderPaymentMethodFee] MONEY            DEFAULT ((0)) NULL,
    PRIMARY KEY CLUSTERED ([WireId] ASC)
);

