CREATE TABLE [dbo].[Partners_WireInPreparation]
(
    [PreparationID] UNIQUEIDENTIFIER NOT NULL, 
    [LSenderId] INT NOT NULL, 
    [LReceiverId] INT NOT NULL, 
    [AgSenderId] INT NOT NULL, 
    [AgSenderCode] VARCHAR(10) NOT NULL, 
    [AgSenderSeq] INT NOT NULL, 
    [AgSenderState] VARCHAR(80) NOT NULL, 
    [AgSenderCity] VARCHAR(80) NOT NULL, 
    [AgSenderCountry] VARCHAR(80) NOT NULL, 
    [AgPayerId] INT NOT NULL, 
    [AgPayerCode] VARCHAR(10) NOT NULL, 
    [DestCountry] VARCHAR(80) NOT NULL, 
    [DestState] VARCHAR(80) NOT NULL, 
    [DestCity] VARCHAR(80) NOT NULL, 
    [BranchId] INT NOT NULL, 
    [SenderId] INT NOT NULL, 
    [ReceiverId] INT NOT NULL, 
    [SenderName] VARCHAR(100) NOT NULL, 
    [ReceiverName] VARCHAR(100) NOT NULL, 
    [PinNumber] VARCHAR(20) NULL, 
    [WireStatus] VARCHAR(30) NOT NULL, 
    [WireDate] DATETIME NOT NULL, 
    [WireDatetime] DATETIME NOT NULL, 
    [OriAmount] MONEY NOT NULL, 
    [OriCurrency] CHAR(3) NOT NULL, 
    [Charges] MONEY NOT NULL, 
    [OtherChg] INT NOT NULL, 
    [AgencyFee] INT NOT NULL, 
    [OriToDestExRate] MONEY NOT NULL, 
    [WireTotalAmount] MONEY NOT NULL, 
    [DestAmount] MONEY NOT NULL, 
    [DestCurrency] CHAR(3) NOT NULL, 
    [AgSenderCommission] MONEY NOT NULL, 
    [TranTypeID] INT NOT NULL, 
    [AccountNumber] VARCHAR(30) NULL, 
    [DeptBankName] VARCHAR(60) NULL, 
    [AccountType] INT NULL, 
    [DeptAdditionalInfo] VARCHAR(60) NULL, 
    [BankBranchCode] VARCHAR(7) NULL, 
    [DeliveryType] CHAR NOT NULL, 
    [SourceApp] INT NOT NULL, 
    [StsComplianceOk] BIT NOT NULL, 
    [StsCancel] SMALLINT NOT NULL, 
    [WirePurpose] VARCHAR(200) NULL, 
    [FundSource] VARCHAR(120) NULL, 
    [Occupation] VARCHAR(80) NULL, 
    [CustMessage] VARCHAR(255) NULL, 
    [MemberCardSwiped] BIT NULL, 
    [SndDOB] DATETIME NULL, 
    [CreatedBy] VARCHAR(15) NOT NULL, 
    [SndRcvRelationship] VARCHAR(80) NULL, 
    [LoyaltyCardNumber] VARCHAR(50) NULL, 
    [CancelReasonId] INT NULL, 
    [SndEmployerName] VARCHAR(120) NULL, 
    [SndEmployerPhone] VARCHAR(20) NULL, 
    [TransacTotalAmount] INT NULL, 
    [PartnerId] INT NULL, 
    [RcvIdNumber] VARCHAR(80) NULL, 
    [F1025AgentFullName] VARCHAR(150) NULL, 
    [CPF] VARCHAR(11) NULL, 
    [PartnerAgencyCode] VARCHAR(10) NOT NULL, 
    [WireStateFee] MONEY NULL, 
    PRIMARY KEY ([PreparationID])
)
